import { createSlice, PayloadAction } from '@reduxjs/toolkit';

export const selectAlertError = (state: any) => state.alerts.error;
export const selectAlertSuccess = (state: any) => state.alerts.success;


export const alertSlice = createSlice({
    name: 'alerts/details',
    initialState: { error: '', success: '' },
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        setAlertError: (state, action: PayloadAction<string>) => {
            state.error = action.payload;
        },
        setAlertSuccess: (state, action: PayloadAction<string>) => {
            state.success = action.payload;
        },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {

    },

});

export const { setAlertError,setAlertSuccess } = alertSlice.actions;

export default alertSlice.reducer;